[tool.black]
exclude='''
/(
    \.git
  | \.idea

  # Both of these are p. common and will never exist in the project itself
  | venv
  | \.venv
)/
'''

[tool.isort]
profile = "black"
src_paths = ["display", "ds", "unique"]